version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
      open-pull-requests-limit: 5
      allow:
          - dependency-type: "production"
      reviewers:
          - "lvchkn"

    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"
      open-pull-requests-limit: 5
      reviewers:
          - "lvchkn"
