version: "3"
services:
    react-app:
        image: ghcr.io/lvchkn/hn-client:latest
        networks:
            - hnfeed
    nginx-fe:
        image: nginx:alpine
        ports:
            - "443:443"
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - /etc/letsencrypt/live/${DOMAIN}/fullchain.pem:/etc/nginx/ssl/${DOMAIN}/fullchain.pem
            - /etc/letsencrypt/live/${DOMAIN}/privkey.pem:/etc/nginx/ssl/${DOMAIN}/privkey.pem
            - /etc/letsencrypt/live/www.${DOMAIN}/fullchain.pem:/etc/nginx/ssl/www.${DOMAIN}/fullchain.pem
            - /etc/letsencrypt/live/www.${DOMAIN}/privkey.pem:/etc/nginx/ssl/www.${DOMAIN}/privkey.pem
            - /etc/nginx/ssl/nginx.crt:/etc/nginx/ssl/nginx.crt
            - /etc/nginx/ssl/nginx.key:/etc/nginx/ssl/nginx.key
        networks:
            - hnfeed
networks:
    hnfeed:
        name: hnfeed_default
        external: true
